name: MY-NODE-APP PIPELINE

on:
  push:
    branches: [main]

jobs:
  Setup-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      # - name: Installing Dependencies
      #   run: npm install

      # - name: Run the app
      #   run: pm2 start npm --name "my-node-app" -- start -- -p 3000

      - name: Building the Docker image
        run: |
          sudo docker build . -t my-node-app
          sudo docker image ls

      - name: Removing the Docker
        run: |
          sudo docker container stop mynodeapp
          sudo docker container rm mynodeapp   
        continue-on-error: true

      - name: Running the App with Docker
        run: |
          sudo docker container run --name mynodeapp -dit -p 3000:3000 my-node-app /bin/bash 
          
